# Generated by Django 4.2.3 on 2023-07-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('patrony', models.CharField(max_length=200, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Тело письма')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема письма')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='SendingTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата попытки')),
                ('time', models.TimeField(verbose_name='Время попытки')),
                ('status', models.CharField(max_length=200, verbose_name='Статус')),
                ('server_status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Статус сервера')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.email')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('periodicity', models.CharField(max_length=200, verbose_name='Периодичность')),
                ('status', models.CharField(max_length=200, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client')),
            ],
            options={
                'verbose_name': 'Настройка рассылки',
                'verbose_name_plural': 'Настройки рассылки',
            },
        ),
        migrations.AddField(
            model_name='email',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsetting'),
        ),
    ]
