# Generated by Django 4.2.3 on 2023-07-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsetting',
            name='periodicity',
            field=models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], max_length=200, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('in_progress', 'Запущена'), ('completed', 'Завершена')], max_length=200, verbose_name='Статус'),
        ),
    ]
