# Generated by Django 4.2.3 on 2023-07-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailingsetting_periodicity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='settings',
            new_name='mailing_setting',
        ),
    ]
