# Generated by Django 4.2.3 on 2023-07-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_rename_settings_email_mailing_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='mailing_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsetting', verbose_name='Настройка рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.client'),
        ),
    ]
