# Generated by Django 4.2.3 on 2023-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_email_mailing_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsetting',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('in_progress', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=200, verbose_name='Статус'),
        ),
    ]
