# Generated by Django 4.2.4 on 2023-08-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailingsetting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsetting',
            name='client',
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='clients',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Клиенты'),
        ),
    ]
