# Generated by Django 4.2.4 on 2023-08-28 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_remove_mailingsetting_client_mailingsetting_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendingtry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sendingtry',
            name='time',
        ),
        migrations.AddField(
            model_name='sendingtry',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.client'),
        ),
        migrations.AddField(
            model_name='sendingtry',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время попытки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sendingtry',
            name='status',
            field=models.CharField(max_length=200, verbose_name='Статус попытки'),
        ),
    ]
