# Generated by Django 4.2.4 on 2023-08-28 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_remove_sendingtry_date_remove_sendingtry_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingsetting',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mailingsetting',
            name='time',
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 12, 49, 54, 345020, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
